version: '3.9'

services:
    redis:
        image: redis
        restart: always
        ports:
            - 6380:6379
        volumes:
            - redis_data_a:/data
        entrypoint: redis-server --appendonly yes

    flower:
        image: mher/flower
        ports:
            - 5555:5555
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - FLOWER_PORT=5555
        depends_on:
            - redis

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus:/etc/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        restart: always

volumes:
    redis_data_a: