# Generated by Django 5.1.4 on 2024-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_trigger_scrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trigger_scrap',
            field=models.BooleanField(default=False),
        ),
    ]
