# Generated by Django 5.1.4 on 2024-12-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product__trigger_scrap_product_trigger_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_trigger_scrap',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trigger_scrap',
        ),
    ]
